_BASE_: ../ytvis22/videomt/vit-large/videomt_online_ViTL.yaml

MODEL:
  BACKBONE:
    NUM_CLASSES: 1
    MVC_WEIGHT: 1.0
    NO_OBJECT_WEIGHT: 0.1

DATASETS:
  DATASET_NEED_MAP: [False]
  DATASET_TYPE: ['video_instance']
  DATASET_TYPE_TEST: ['video_instance']
  DATASET_RATIO: [1.0]
  TRAIN: ("custom_train",)
  TEST: ("custom_val",)

SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.00002
  MAX_ITER: 40000
  WARMUP_STEPS: [2000, 4000]
  LLRD: 0.75
INPUT:
  SAMPLING_FRAME_NUM: 5

OUTPUT_DIR: './output_videomt_custom_ViTL'
